### PR TITLE
built static assets for github pages

### PR DESCRIPTION
**Pull request by grzegorz-bielski**
The [website is down](https://github.com/sangria-graphql/sangria/issues/502), but we could use [github pages as a temporary solution](https://github.com/sangria-graphql/sangria-website/issues/74).
I've built assets in the default GH pages folder - `docs` and updated the readme.

Next steps:
1.  GitHub pages configuration in the [`Settings` tab](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source)
2.  (optional) renaming the repo to ` sangria-graphql.github.io` so we will get a nice domain
3. updating all readmes/docs, so they include the link to the new site

### CODE REVIEW

**Comment by rodrigorn** [comment]
@yanns what do you think? Could you configure the repository?

**Comment by yanns** [comment]
@grzegorz-bielski Thanks for the PR! I've somehow missed it.
@rodrigorn @grzegorz-bielski should I give one of you of the needed permissions to finalize this?

**Comment by grzegorz-bielski** [comment]
@yanns Sure, that would be convenient. I can finalize it

**Comment by yanns** [comment]
@grzegorz-bielski I've added you to the [contributors(]https://github.com/orgs/sangria-graphql/teams/contributors) team. I hope this is sufficient. Thanks a lot!!!

**Comment by grzegorz-bielski** [comment]
@yanns Sorry, looks like this is not enough 😢 . I can't see the `Settings` tab in the GitHub for this repository.

**Comment by yanns** [comment]
@grzegorz-bielski I gave you more rights. Can you check again?

**Comment by grzegorz-bielski** [comment]
@yanns Thx, it worked! 
http://sangria-graphql.github.io/sangria-website/ - seems like paths need to be adjusted first. I'll try to address it in a subsequent PR.

**Comment by yanns** [comment]
Awesome!
thx a lot!!

**Comment by rodrigorn** [comment]
@grzegorz-bielski is there anything I can help you with?

**Pull request merged**
